version: '3.8'

services:
  # Motor 1: Tu backend principal
  api-node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

  # Motor 2: Tus estadísticas
  api-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    env_file:
      - .env

      
